In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
df['target']=data.target

In [6]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.drop("target",axis=1)

In [9]:
y=df.target

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [11]:
from sklearn.svm import SVC

In [12]:
model = SVC()
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(SVC(),X,y, cv=3)

array([0.96, 0.98, 0.94])

In [15]:
cross_val_score(SVC( C=1.0,kernel='linear',gamma='scale',),X,y, cv=3)

array([1.  , 1.  , 0.98])

In [16]:
cross_val_score(SVC( C=10.0,kernel='rbf'),X,y, cv=3)

array([0.98, 1.  , 0.94])

In [17]:
cross_val_score(SVC( C=10.0,kernel='linear'),X,y, cv=3)

array([1.  , 0.94, 0.98])