In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("D:\CSV files\car_data1.csv")

In [3]:
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [4]:
df.tail()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
296     city  2016           9.50           11.6       33988    Diesel   
297     brio  2015           4.00            5.9       60000    Petrol   
298     city  2009           3.35           11.0       87934    Petrol   
299     city  2017          11.50           12.5        9000    Diesel   
300     brio  2016           5.30            5.9        5464    Petrol   

    Seller_Type Transmission  Owner  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0

In [5]:
X = df.drop("Selling_Price",axis=1)

In [6]:
y = df.Selling_Price

In [7]:
X.drop(['Car_Name','Present_Price'],axis=1, inplace=True)

In [8]:
X.head()

Year  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0  2014       27000    Petrol      Dealer       Manual      0
1  2013       43000    Diesel      Dealer       Manual      0
2  2017        6900    Petrol      Dealer       Manual      0
3  2011        5200    Petrol      Dealer       Manual      0
4  2014       42450    Diesel      Dealer       Manual      0

In [9]:
X.shape

(301, 6)

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Year          301 non-null    int64 
 1   Kms_Driven    301 non-null    int64 
 2   Fuel_Type     301 non-null    object
 3   Seller_Type   301 non-null    object
 4   Transmission  301 non-null    object
 5   Owner         301 non-null    int64 
dtypes: int64(3), object(3)
memory usage: 14.2+ KB


In [11]:
X.isnull().sum()

Year            0
Kms_Driven      0
Fuel_Type       0
Seller_Type     0
Transmission    0
Owner           0
dtype: int64

In [12]:
X['Current_year']= 2025

In [13]:
X.head()

Year  Kms_Driven Fuel_Type Seller_Type Transmission  Owner  Current_year
0  2014       27000    Petrol      Dealer       Manual      0          2025
1  2013       43000    Diesel      Dealer       Manual      0          2025
2  2017        6900    Petrol      Dealer       Manual      0          2025
3  2011        5200    Petrol      Dealer       Manual      0          2025
4  2014       42450    Diesel      Dealer       Manual      0          2025

In [14]:
X['Year'] = X['Current_year'] - X['Year']

In [15]:
X.head()

Year  Kms_Driven Fuel_Type Seller_Type Transmission  Owner  Current_year
0    11       27000    Petrol      Dealer       Manual      0          2025
1    12       43000    Diesel      Dealer       Manual      0          2025
2     8        6900    Petrol      Dealer       Manual      0          2025
3    14        5200    Petrol      Dealer       Manual      0          2025
4    11       42450    Diesel      Dealer       Manual      0          2025

In [16]:
X.drop("Current_year", axis=1,inplace=True)

In [17]:
X.head()

Year  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0    11       27000    Petrol      Dealer       Manual      0
1    12       43000    Diesel      Dealer       Manual      0
2     8        6900    Petrol      Dealer       Manual      0
3    14        5200    Petrol      Dealer       Manual      0
4    11       42450    Diesel      Dealer       Manual      0

In [18]:
X['Owner'].unique()

array([0, 1, 3])

In [19]:
X['Seller_Type'].unique()

array(['Dealer', 'Individual'], dtype=object)

In [20]:
X['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [21]:
X['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [22]:
X = pd.get_dummies(data=X, columns=['Fuel_Type','Transmission','Seller_Type'],drop_first=True, dtype=int)

In [23]:
X.head()

Year  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0    11       27000      0                 0                 1   
1    12       43000      0                 1                 0   
2     8        6900      0                 0                 1   
3    14        5200      0                 0                 1   
4    11       42450      0                 1                 0   

   Transmission_Manual  Seller_Type_Individual  
0                    1                       0  
1                    1                       0  
2                    1                       0  
3                    1                       0  
4                    1                       0

In [24]:
X.shape

(301, 7)

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
model = MinMaxScaler()

In [27]:
model.fit_transform(df[["Year", "Kms_Driven", "Owner"]])

array([[0.73333333, 0.05305305, 0.        ],
       [0.66666667, 0.08508509, 0.        ],
       [0.93333333, 0.01281281, 0.        ],
       [0.53333333, 0.00940941, 0.        ],
       [0.73333333, 0.08398398, 0.        ],
       [1.        , 0.00314515, 0.        ],
       [0.8       , 0.03662863, 0.        ],
       [0.8       , 0.06592392, 0.        ],
       [0.86666667, 0.03958559, 0.        ],
       [0.8       , 0.08381782, 0.        ],
       [0.93333333, 0.00327327, 0.        ],
       [0.8       , 0.1011011 , 0.        ],
       [0.8       , 0.02902903, 0.        ],
       [0.8       , 0.05105105, 0.        ],
       [0.4       , 0.15400801, 0.        ],
       [0.86666667, 0.08508509, 0.        ],
       [0.8       , 0.08243844, 0.        ],
       [0.86666667, 0.08508509, 0.        ],
       [0.8       , 0.07007007, 0.        ],
       [0.46666667, 0.08196597, 0.        ],
       [0.86666667, 0.04904905, 0.        ],
       [0.93333333, 0.0038038 , 0.        ],
       [0.

In [28]:
X['Year'] = model.fit_transform(X[["Year"]])

In [29]:
X.head()

Year  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0  0.266667       27000      0                 0                 1   
1  0.333333       43000      0                 1                 0   
2  0.066667        6900      0                 0                 1   
3  0.466667        5200      0                 0                 1   
4  0.266667       42450      0                 1                 0   

   Transmission_Manual  Seller_Type_Individual  
0                    1                       0  
1                    1                       0  
2                    1                       0  
3                    1                       0  
4                    1                       0

In [30]:
X["Kms_Driven"] = model.fit_transform(X[["Kms_Driven"]])

In [31]:
X.head()

Year  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0  0.266667    0.053053      0                 0                 1   
1  0.333333    0.085085      0                 1                 0   
2  0.066667    0.012813      0                 0                 1   
3  0.466667    0.009409      0                 0                 1   
4  0.266667    0.083984      0                 1                 0   

   Transmission_Manual  Seller_Type_Individual  
0                    1                       0  
1                    1                       0  
2                    1                       0  
3                    1                       0  
4                    1                       0

In [32]:
X["Owner"] = model.fit_transform(X[["Owner"]])

In [33]:
X.head()

Year  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0  0.266667    0.053053    0.0                 0                 1   
1  0.333333    0.085085    0.0                 1                 0   
2  0.066667    0.012813    0.0                 0                 1   
3  0.466667    0.009409    0.0                 0                 1   
4  0.266667    0.083984    0.0                 1                 0   

   Transmission_Manual  Seller_Type_Individual  
0                    1                       0  
1                    1                       0  
2                    1                       0  
3                    1                       0  
4                    1                       0

In [34]:
X.shape

(301, 7)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
X_train.shape

(201, 7)

In [38]:
X_test.shape

(100, 7)

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
model = LinearRegression()

In [41]:
model.fit(X_train,y_train)

LinearRegression()

In [42]:
model.score(X_test,y_test)

0.6277335827814441

In [43]:
y_pred= model.predict(X_test)

In [44]:
y_pred

array([ 5.55891467,  5.13809034,  9.24487324, -0.44843517,  4.36501934,
       10.06065474,  1.03506402,  0.67358409,  1.28402948,  9.77655851,
       10.79143905,  0.4733749 ,  8.80260514,  5.76774997,  9.48258726,
        4.45702242,  0.09876828,  5.42351049,  1.55774813,  1.53074466,
        0.39461477, 10.26861618,  9.14106739,  3.70206344,  0.73734229,
        4.05229192,  4.42765239,  3.78832453,  1.56674929,  1.29903141,
        0.4096167 ,  9.84406719, -0.43104174,  2.96266802, 10.35700004,
        4.64023442,  4.48503102,  3.2716412 ,  4.42831998,  3.52060666,
        2.14451247,  6.3135281 ,  4.58022671,  0.80110049, 10.02713293,
        0.46962442,  4.6594594 ,  7.87050149,  4.32751076,  9.21536445,
        8.58813662,  1.54087096, 14.31541109, 14.78333815, 10.13196641,
        9.44962899,  4.81978596, 10.3232007 ,  2.34643188,  9.39076892,
        0.46212345, -1.36410326,  1.53862067, -0.93272315,  4.93795615,
        1.26415193, 13.99893694, 14.28915771,  4.87343286,  0.04

In [45]:
y_test[:5]

177     0.35
289    10.11
228     4.95
198     0.15
60      6.95
Name: Selling_Price, dtype: float64

In [46]:
y_pred[:5]

array([ 5.55891467,  5.13809034,  9.24487324, -0.44843517,  4.36501934])